### ISSUE TITLE
Pod install gives no pod spec found error on native swift template

### ISSUE THREAD

**Issue by ankitaporwal** [forcedotcom/SalesforceMobileSDK-Templates#106]
Hi @bhariharan,

Please find the below error when i run pod install in the native swift template Ankita-Porwal:iOSNativeSwiftTemplate ankita$ pod install
Analyzing dependencies
Pre-downloading: `PromiseKit` from `https://github.com/mxcl/PromiseKit`, tag `5.0.3`
Fetching podspec for `SalesforceAnalytics` from `mobile_sdk/SalesforceMobileSDK-iOS`
[!] No podspec found for `SalesforceAnalytics` in `mobile_sdk/SalesforceMobileSDK-iOS`
Ankita-Porwal:iOSNativeSwiftTemplate ankita$ 

I need your help resolve this issue 

Thanks,
AP

**Comment by bhariharan** [comment]
@ankitaporwal As I mentioned in the other post, please use [forceios](https://www.npmjs.com/package/forceios) to generate an app. This will set up the dependencies correctly for consumption. In older versions of `Mobile SDK`, our libraries were under `node_modules`. We have changed this to `mobile_sdk` in recent versions. I suspect the missing folder is causing this issue. Using `forceios@6.0` to generate an app should resolve this issue. Also, this forum is reserved for known issues/bug with our code. Please use our [Google+ community](https://plus.google.com/u/1/communities/114225252149514546445?cfem=1) for issues/discussions such as this.

**Comment by wmathurin** [comment]
In your project's Podfile, add the SalesforceMobileSDK-iOS-Specs repo as a source. Make sure that you put this entry first, before the CocoaPods source path.
```
target 'YourAppName' do
source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git' # needs to be first 
source 'https://github.com/CocoaPods/Specs.git'
```
For more information see https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/ios_cocoapods.htm
