### ISSUE TITLE
React Native appdelegate.m file uses old approach to js bundle location

### ISSUE THREAD

**Issue by socialsuiteDan** [forcedotcom/SalesforceMobileSDK-Templates#107]
The template for React Native apps on iOS currently requires the user to comment/uncomment different lines of code to switch the js bundle location from the development server to the on-device packaged version. The standard template for react native apps has a different mechanism where the js bundle location is tied to which build configuration is being run, which is much easier to work with (and is already the way the Android build works). It looks like this was switched over quite a while back, around react native version 0.29.

Would it be possible to switch the appdelegate.m file in the SDK template to use the new approach? This would also make it much easier to install other react native libraries that modify the appdelegate.m file, as the installation steps typically expect the file to be based on the new template.

**Comment by wmathurin** [comment]
Thanks for the feedback.
We will look at updating the template for our next release.

**Comment by wmathurin** [comment]
Fixed in our next release: see https://github.com/forcedotcom/SalesforceMobileSDK-Templates/pull/110
