### ISSUE TITLE
Please update to more recent node version

### ISSUE THREAD

**Issue by fobin** [forcedotcom/SalesforceMobileSDK-Templates#153]
Trying to run forcedroid and getting this error:

> Missing tools
>
> Installed node version (10.9.0) is more than the maximum supported version (8.11).  Please downgrade your version of node.

**Comment by ahayes91** [comment]
@fobin how did you fix this? I'm following the steps to install forcedroid here https://trailhead.salesforce.com/en/content/learn/projects/mobilesdk_setup_dev_tools/mobilesdk_setup_android and getting the following error:
`forcedroid version
Missing tools

Installed node version (10.13.0) is more than the maximum supported version (8.11).  Please downgrade your version of node.`

**Comment by fobin** [comment]
@ahayes91 When installing node you need to make sure you install version 8. Here are some tips installing via Home-brew: https://medium.com/@katopz/how-to-install-specific-nodejs-version-c6e1cec8aa11
