### ISSUE TITLE
Couldn't refresh token issue

### ISSUE THREAD

**Issue by ashishalgo** [forcedotcom/SalesforceMobileSDK-Templates#164]
Hello Team,

We are creating Android and iOS Native app using React Native Framework v0.50.4. We are stuck in an issue described as below.

We are consistently getting 'Could not refresh token' error from Salesforce mobile sdk on production environment during syncing process. The same is working fine on Sandbox environment. We have also created Connected Apps on both the environments.

We have taken a template from https://github.com/forcedotcom/SalesforceMobileSDK-Templates/tree/master/SmartSyncExplorerReactNative

We have also posted the same issue on SalesforceMobileSDK Google group but didn't find the resolution to fix this issue. 
You can find the url below : 
https://plus.google.com/108862923721534440328/posts/hDUMZRucG6Z
Salesforce SDK version 6.2
React Native version 0.55.4

There is a Poor Error handling on SalesforceMobileSDK due to which we are not able to find the exact issue, we are only getting couldn't refresh token all the time.

I would really appreciate if you could help me out to resolve this issue.

Regards,
Vantage

**Comment by wmathurin** [comment]
If it works fine in one environment and not another, then it must be a server configuration issue. 
Could you compare both configurations? Are you using a different refresh token policy?

**Comment by rishabh-2493** [comment]
Hi @ashishalgo ,
I am facing the same issue. Did you get any solution to it?

Regards,
Rishabh
