### ISSUE TITLE
Delaying Authentication iOS

### ISSUE THREAD

**Issue by gla5001** [forcedotcom/SalesforceMobileSDK-Templates#179]
It appears that setting

```
<key>shouldAuthenticate</key>
	<false/>
```

in the bootconfig.plist should prevent the login screen from launching on app init, but that does not seem to be the case. How do you prevent the login screen from launching on init? This worked prior to the v7.0.0 release, but it was all handled in the AppDelegate file?

**Comment by wmathurin** [comment]
Here is a workaround.
Edit your `AppDelegate.swift` file,  in `application (_:didFinishLaunchingWithOptions:)`, replace
```swift
AuthHelper.loginIfRequired {
    self.setupRootViewController()
}
```
With
```swift
if (SalesforceManager.shared.bootConfig?.shouldAuthenticateOnFirstLaunch) {
    AuthHelper.loginIfRequired {
        self.setupRootViewController()
    }
} else {
    self.setupRootViewController()
}
```

**Comment by gla5001** [comment]
thanks. i'll try it out

**Comment by gla5001** [comment]
@wmathurin workaround seems to work. thanks.

**Comment by wmathurin** [comment]
We are fixing loginIfRequired to check shouldAuthenticate in our next release (https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2756) so that work around won't be needed anymore then (but it won't hurt if you leave it).
