### ISSUE TITLE
[Question] How to login to Community React Native

### ISSUE THREAD

**Issue by gla5001** [forcedotcom/SalesforceMobileSDK-Templates#182]
I've been digging around in the iOS code (have not tried android yet) trying to figure out how to login into a community site. I am able to change the `SFDCOAuthLoginHost` in the info.plist to my community login url (<my community>-developer-edition.na53.force.com/login), and I can see that is builds the auth url with that host. But it goes through the `brandedAuthorizeURL` method, which tacks `/services/oauth2/authorize?...` onto the url, which sends the login page to a not found page. I just want to hit `<my community>-developer-edition.na53.force.com/login` and auth through the community site. Is there a way to do this or is it not supported?

**Comment by bhariharan** [comment]
`/services/oauth2/authorize` is the standard way to performing `OAuth2` login on a mobile device within the container. If the login host is configured to point to your community URL, i.e. if `SFDCOAuthLoginHost` is set to `...-developer-edition.na53.force.com` (without the `/login`), it should work.

**Comment by gla5001** [comment]
@bhariharan yup. that works. i should've known better and tried that. thanks.

**Comment by gla5001** [comment]
@bhariharan where is the login host defined for Android? Having trouble finding it. Is it configurable for Android like how it is for iOS by including it in the info.plist?

**Comment by wmathurin** [comment]
It's done through the server.xml file.
See the [doc here](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/oauth_custom_login_host.htm)

**Comment by gla5001** [comment]
Great. Thanks.
