### ISSUE TITLE
How to see my contacts from salesforce

### ISSUE THREAD

**Issue by zishe** [forcedotcom/SalesforceMobileSDK-Templates#186]
I installed an app, logged in and it works correctly. When I sign in to salesforce website, I can see I have few contacts. But when I sign in in a mobile app (react-native) I don't see any contacts. And if I create a contact it's not saving to my account.

**Comment by zishe** [comment]
Is there a way I can do that without any backend?

**Comment by bhariharan** [comment]
@zishe The sample app is intended to work with the Salesforce backend. Also, this forum is reserved for bugs/issues with our code. For general queries, please use our [discussion forums](https://plus.google.com/u/1/communities/114225252149514546445?cfem=1).
