### ISSUE TITLE
iOS 13 template does not map Accounts correctly

### ISSUE THREAD

**Issue by gonardfreeman** [forcedotcom/SalesforceMobileSDK-Templates#250]
After I've created project I cannot see in ui any records but from debug I can see that I fetch them
I assume loadFromSmartStore func havent called or it mapped contacts in wrong way
### Steps to reproduce:
1.  Create project with iOS 13 swift template;
2. Change token and cb url
3. launch app

**Comment by brandonpage** [comment]
[This has been fixed in the dev branch](https://github.com/forcedotcom/SalesforceMobileSDK-Templates/pull/249) and will be included in the next release.  Thanks for reporting!
