### ISSUE TITLE
"Can't find variable: oauth" error when signing out

### ISSUE THREAD

**Issue by Sheehanigans** [forcedotcom/SalesforceMobileSDK-Templates#251]
MobileSyncExplorerReactNative project
When I try to use the logout button in the SearchScreen, I get the following error:
ReferenceError: Can't find variable: oauth
onPress 
SearchScreen.js:159:50
...
Fix:
Added the following import statement on line 36 of SearchScreen:
import {oauth} from 'react-native-force';

**Comment by bhariharan** [comment]
@Sheehanigans This is fixed [here](https://github.com/forcedotcom/SalesforceMobileSDK-Templates/pull/248). It will be a part of our next release.
