### ISSUE TITLE
Upgrade iOS sdk for react native template

### ISSUE THREAD

**Issue by gla5001** [forcedotcom/SalesforceMobileSDK-Templates#257]
With Apple requiring all apps to use iOS sdk 13 or later by June 30, 2020. Any plans to upgrade the react native template? It looks like it uses 12.2.

**Comment by wmathurin** [comment]
The Mobile SDK deployment target is 12.2, but its base SDK is 13 (it builds again iOS SDK 13, but will work on 12.2) so we are already satisfying Apple requirements.
