### ISSUE TITLE
forceios createWithTemplate failing

### ISSUE THREAD

**Issue by mr0perfect** [forcedotcom/SalesforceMobileSDK-Templates#262]
I'm trying to create a template App using forceios but this is failing during pod dependencies installation.
forceios version-6.2.0
npm veriosn - 5.6.0

$ forceios createwithtemplate --templaterepouri=https://github.com/forcedotcom/SalesforceMobileSDK-Templates/MobileSyncExplorerSwift
Enter your application name: SDKSample
Enter your package name: com.bestapp.ios
Enter your organization name (Acme, Inc.): bestapp.com
Enter output directory for your app (leave empty for the current directory): 

/Users/mr0perfect/SDKSample /Users/mr0perfect
Installing sdk dependencies
Cloning into 'mobile_sdk/SalesforceMobileSDK-iOS'...
remote: Enumerating objects: 1063, done.
remote: Counting objects: 100% (1063/1063), done.
remote: Compressing objects: 100% (961/961), done.
remote: Total 1063 (delta 464), reused 261 (delta 72), pack-reused 0
Receiving objects: 100% (1063/1063), 26.45 MiB | 2.93 MiB/s, done.
Resolving deltas: 100% (464/464), done.
Note: checking out '33181112f6c284285a0132897fc6b24988aedff2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Installing pod dependencies
Update all pods
Updating local specs repositories
Cloning spec repo `cocoapods-` from `https://cdn.cocoapods.org/`
**[!] Unable to add a source with url `https://cdn.cocoapods.org/` named `cocoapods-`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.**
/Users/mr0perfect
**forceios failed**

**Command failed: pod update**

**Comment by bhariharan** [comment]
Which version of `cocoapods` do you have? You need `1.8.4`.

**Comment by mr0perfect** [comment]
My cocoapods version is **1.4.0**. 
So I need to update to the version you told and give it a try.
Thanks
@bhariharan What is the best place to reach out to you for an SDK related **doubt**?(not an issue)

**Comment by bhariharan** [comment]
Yes, you need `1.8.4` for CDN support. You can post queries on [Salesforce Stack Exchange](https://salesforce.stackexchange.com/).
