### ISSUE TITLE
React Native Template does not have auto linking for ios

### ISSUE THREAD

**Issue by lchnnl** [forcedotcom/SalesforceMobileSDK-Templates#273]
When creating a new react-native app using forcereact, then the podfile does not include the necessary changes as described (here)[https://reactnative.thenativebits.com/courses/upgrading-react-native/upgrade-to-react-native-0.60/]

When I add a library using `npm install --save <package-name` and run `pod install` the newly added package is not added.

Steps to reproduce
1. Create a new app using `forcereact createWithTemplate --templaterepouri=ReactNativeTemplate`
2. Browse the folder of the app
3. run `npm install --save react-native-camera`
This package supports autolinking
4. run `npx pod-install`

After running the last command you'll see that no pods are linked.

**Comment by wmathurin** [comment]
Thanks for reporting. We will take a look.

**Comment by wmathurin** [comment]
With this change https://github.com/forcedotcom/SalesforceMobileSDK-Templates/pull/304, forcereact generated apps will auto-link their dependencies.
