### ISSUE TITLE
MobileSyncExplorerReactNative: Login after being logged out result in Fatal error

### ISSUE THREAD

**Issue by lchnnl** [forcedotcom/SalesforceMobileSDK-Templates#280]
Installed templated. After being logged out (`oauth.logout()`), I try to relogin with a different account. The app will then throw a fatal error and metro bundler is constantly restarting and looping constantly.

Salesforce Mobile SDK v8.1
React Native v0.61

Steps to reproduce
1. Installed template MobileSyncExplorerReactNative using forcereact
2. start bundler `npm run start`
3. build ios app `npx react-native run-ios`
4. Login screen appears, login with a credential
5. Click on the logout button (upper right)
6. Login screen re-appears, enter credential of different user
7. Ios app throws fatal error. Bundler is constantly restarting.

**Comment by wmathurin** [comment]
The issue is not reproducible with the latest code dev (which will soon be shipped as 8.2).
Please try again after upgrading (next week) and re-open an issue if you still have a problem.

**Comment by lchnnl** [comment]
> The issue is not reproducible with the latest code dev (which will soon be shipped as 8.2).
> Please try again after upgrading (next week) and re-open an issue if you still have a problem.

Hi Wolfgang,

Do you have any idea when sdk v8.3 will be published? We are hesitating whether we should upgrade to v8.2 now or wait a little bit longer for v8.3 to come out. Because it requires some efforts to upgrade the SDK.

Thanks!!

**Comment by bhariharan** [comment]
@lchnnl `8.3` is tentatively slated for early October at this time #safeharbor
