### ISSUE TITLE
Remote access consumer key

### ISSUE THREAD

**Issue by gonardfreeman** [forcedotcom/SalesforceMobileSDK-Templates#291]
Hey!
Got a question!
Our company got a product on app exchange and we've want to build native app. How we could implement dynamic access key so users could login at any org? any ideas?

**Comment by wmathurin** [comment]
Not sure what you mean by "dynamic access key".
When you setup a connected app, it will be available in all orgs. Users of the mobile app that uses the consumer key for the connected app will be able to log in to any orgs. Admins of a given org can "install the connected app" in their org if they want to be able to define some of the policies (e.g. pin code). For more information see: https://help.salesforce.com/articleView?id=connected_app_how_to_install.htm&type=5

**Comment by wmathurin** [comment]
Closing issue - for further discussion, we recommend you post on https://salesforce.stackexchange.com/questions/tagged/mobilesdk
