### ISSUE TITLE
How to popup soup through REST API

### ISSUE THREAD

**Issue by pwketankulkarni** [forcedotcom/SalesforceMobileSDK-Templates#295]
i am integrating salesforce with react native for the first time, I am using forcereact command. I want to popup soup through REST API, I referred [this link](https://developer.salesforce.com/docs/atlas.enus.noversion.mobile_sdk.meta/mobile_sdk/offline_populate_soup.htm) but they have mentioned only hybrid apps and native apps.
Can anyone guide me how I can call REST API. For example in following function I want to call REST API

```
function syncUpContacts() {
	if (syncInFlight) {
		console.log("Not starting syncUp - sync already in fligtht");
		return Promise.resolve();
	}

	console.log("Starting syncUp");
	syncInFlight = true;
	const fieldlist = [
		"FirstName",
		"LastName",
		"Title",
		"Email",
		"MobilePhone",
		"Department",
	];
	return syncUp(false, {}, "contacts", {
		mergeMode: mobilesync.MERGE_MODE.OVERWRITE,
		fieldlist,
	}).then(() => {
		console.log("syncUp completed or failed");
		syncInFlight = false;
		emitSmartStoreChanged();
	});
}
```

**Comment by wmathurin** [comment]
The React Native APIs are very similar to the hybrid APIs.
Your best bet is to look at the [smartstore](https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/blob/master/src/react.force.smartstore.js) and [network](https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/blob/master/src/react.force.net.js) modules.
You can also look at the template apps: [this one](https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/master/ReactNativeTemplate/app.js#L59) does a rest api call and [this one](https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/master/MobileSyncExplorerReactNative/js/StoreMgr.js#L130) writes to SmartStore.

If you have further questions, please post them on [stack exchange](https://salesforce.stackexchange.com/questions/tagged/mobilesdk).
Github issues are meant to be used for bugs or enhancement requests.
