### ISSUE TITLE
Is it possible to use same syncName(SOUP) for different target/query for same sObject ?

### ISSUE THREAD

**Issue by vivekdeshmane** [forcedotcom/SalesforceMobileSDK-Templates#299]
Hi Team,

We are trying to pull account data using two queries for same syncName . However, SDK overwriting/deleting  records which were pulled out in first query/target instead appending records from second query in same syncName/SOUP. 

SDK version: 8.2.0
React-native version: 0.63.2
React version: 16.11.0

Best Regards,
-Vivek

**Comment by wmathurin** [comment]
Yes it's possible. Please see the discussion here: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/3270
