### ISSUE TITLE
iOS build fails

### ISSUE THREAD

**Issue by paritosh-yadav** [forcedotcom/SalesforceMobileSDK-Templates#303]
Hi,
I'm getting this failure when i run the project in Xcode.

Steps to regenrate:-
1. Create project with "forcereact createwithtemplate"
2. Open the .xcworkspace file in ios directory
3. run project
  
![Screenshot 2021-02-04 at 2 10 50 PM](https://user-images.githubusercontent.com/29055750/106866830-f1378b00-66f2-11eb-967b-beaf249c82ed.png)

@bhariharan @wmathurin

**Comment by bhariharan** [comment]
This was fixed as a part of [this PR](https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/212). It will be a part of our upcoming release, `9.0`.

**Comment by paritosh-yadav** [comment]
Hi @bhariharan , we're running out of deadline, when can we expect the rollout of release 9. We have restriction for Xcode version so we can't use Xcode 11.

Thanks for the prompt response, really appreciate your help on this.

**Comment by wmathurin** [comment]
9.0 is scheduled to be released next week.
