### ISSUE TITLE
React Native Typescript template uses wrong @types/react

### ISSUE THREAD

**Issue by rpander93** [forcedotcom/SalesforceMobileSDK-Templates#306]
package.json uses ^17.0.0 for @types/react while the react dependency is at 16.13.1 which is conflicting.

https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/e12a45c428c20235a809e03b5ade4e97bb2c2e84/ReactNativeTypeScriptTemplate/package.json#L31

**Comment by wmathurin** [comment]
Thanks for reporting.
Fix in https://github.com/forcedotcom/SalesforceMobileSDK-Templates/pull/307
In the meantime, you can edit the package.json of the generated app.

**Comment by wmathurin** [comment]
Actually if I try to use @types/react 16.x.x, I get [these](https://stackoverflow.com/questions/52399839/duplicate-identifier-librarymanagedattributes) kinds of errors. I don't get any errors when using 17.

**Comment by rpander93** [comment]
Yes, probably because `"@types/react-test-renderer": "^17.0.0",` has defines an explicit dependency on @types/react@^17.0 so you'll get multiple copies (as is stated as the root cause in the issue you linked).

Run `yarn why @types/react` to see why it has been installed

**Comment by wmathurin** [comment]
Fixed with https://github.com/forcedotcom/SalesforceMobileSDK-Templates/pull/309 (will be in our next release).
