### ISSUE TITLE
Repo in detached state

### ISSUE THREAD

**Issue by gonardfreeman** [forcedotcom/SalesforceMobileSDK-Templates#308]
While creating project with `forceios createwithtemplate --templaterepouri=iOSNativeSwiftTemplate` forceios uses detached branch with message:

```
Note: switching to 'cb3dcb63f261fda472ca9f0a96b34002b346342a'.
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.
```

**Comment by wmathurin** [comment]
That's not an error - you can safely ignore that warning. 
The podfile of the generated app points to a local shallow clone of the SalesforceMobileSDK-iOS repo.
