### ISSUE TITLE
Can't build  ios project after running forcereact create

### ISSUE THREAD

**Issue by huyvuskedulo** [forcedotcom/SalesforceMobileSDK-Templates#310]
I'm not able to build the Salesforce React-native project after creating forcereact create.

Here is the command line that i used to create the project:
` forcereact create --platform=ios,android --appname=CoolReact --packagename=com.test.my_new_app --organization="Acme Widgets, Inc." --outputdir=CoolReact`
This command run fine after all. There is no error throwing

Here is what's about the error throw after i open the ios proejct via .xcworkspace file and build:
`Ld /Users/huyvu/Library/Developer/Xcode/DerivedData/CoolReact-ggmknehqtfibaccifesgdlgestia/Build/Products/Debug-iphonesimulator/RNScreens/RNScreens.framework/RNScreens normal (in target 'RNScreens' from project 'Pods')
    cd /Users/huyvu/Workplaces/CoolReact/ios/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios9.0-simulator -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk -L/Users/huyvu/Library/Developer/Xcode/DerivedData/CoolReact-ggmknehqtfibaccifesgdlgestia/Build/Products/Debug-iphonesimulator/RNScreens -F/Users/huyvu/Library/Developer/Xcode/DerivedData/CoolReact-ggmknehqtfibaccifesgdlgestia/Build/Products/Debug-iphonesimulator/RNScreens -F/Users/huyvu/Library/Developer/Xcode/DerivedData/CoolReact-ggmknehqtfibaccifesgdlgestia/Build/Products/Debug-iphonesimulator/DoubleConversion -F/Users/huyvu/Library/Developer/Xcode/DerivedData/CoolReact-ggmknehqtfibaccifesgdlgestia/Build/Products/Debug-iphonesimulator/Folly -F/Users/huyvu/Library/Developer/Xcode/DerivedData/CoolReact-ggmknehqtfibaccifesgdlgestia/Build/Products/Debug-iphonesimulator/React-Core -F/Users/huyvu/Library/Developer/Xcode/DerivedData/CoolReact-ggmknehqtfibaccifesgdlgestia/Build/Products/Debug-iphonesimulator/React-cxxreact -F/Users/huyvu/Library/Developer/Xcode/DerivedData/CoolReact-ggmknehqtfibaccifesgdlgestia/Build/Products/Debug-iphonesimulator/React-jsi -F/Users/huyvu/Library/Developer/Xcode/DerivedData/CoolReact-ggmknehqtfibaccifesgdlgestia/Build/Products/Debug-iphonesimulator/React-jsiexecutor -F/Users/huyvu/Library/Developer/Xcode/DerivedData/CoolReact-ggmknehqtfibaccifesgdlgestia/Build/Products/Debug-iphonesimulator/React-jsinspector -F/Users/huyvu/Library/Developer/Xcode/DerivedData/CoolReact-ggmknehqtfibaccifesgdlgestia/Build/Products/Debug-iphonesimulator/Yoga -F/Users/huyvu/Library/Developer/Xcode/DerivedData/CoolReact-ggmknehqtfibaccifesgdlgestia/Build/Products/Debug-iphonesimulator/glog -filelist /Users/huyvu/Library/Developer/Xcode/DerivedData/CoolReact-ggmknehqtfibaccifesgdlgestia/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNScreens.build/Objects-normal/x86_64/RNScreens.LinkFileList -install_name @rpath/RNScreens.framework/RNScreens -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/huyvu/Library/Developer/Xcode/DerivedData/CoolReact-ggmknehqtfibaccifesgdlgestia/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNScreens.build/Objects-normal/x86_64/RNScreens_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -framework Foundation -framework React -Xlinker -no_adhoc_codesign -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/huyvu/Library/Developer/Xcode/DerivedData/CoolReact-ggmknehqtfibaccifesgdlgestia/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNScreens.build/Objects-normal/x86_64/RNScreens_dependency_info.dat -o /Users/huyvu/Library/Developer/Xcode/DerivedData/CoolReact-ggmknehqtfibaccifesgdlgestia/Build/Products/Debug-iphonesimulator/RNScreens/RNScreens.framework/RNScreens
`

`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RCTImageLoader", referenced from:
      objc-class-ref in RNSScreenStackHeaderConfig.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

I'm really appreciate if anyone have any ideas why this is happening? I tried to remove pod folder and run pod install but it has same issue after all

**Comment by wmathurin** [comment]
Can you tell us the versions of Mobile SDK, XCode and MacOS you are using?

**Comment by yashaRO** [comment]
Here ya go, had the same issue.
#https://github.com/software-mansion/react-native-screens/issues/842#issuecomment-790498006

Add this to the podfile
`  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if pod.name.eql?('RNScreens')
        def pod.build_type
          Pod::BuildType.static_library
        end
      end
    end
  end`

**Comment by wmathurin** [comment]
So did the fix suggested [here](https://github.com/software-mansion/react-native-screens/issues/842#issuecomment-791329243) work for you?

**Comment by huyvuskedulo** [comment]
Yes, the suggestion is working for me, thanks everybody.
