### ISSUE TITLE
How to implement a sync up for a custom object ?

### ISSUE THREAD

**Issue by NadjibSb** [forcedotcom/SalesforceMobileSDK-Templates#317]
is there any samples showing how to implement custom sync up target ?

**Comment by wmathurin** [comment]
Please check the documentation for [custom sync down target](https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/entity_framework_native_down_target_def.htm) and [custom sync up target](https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/entity_framework_native_up_target_def.htm).

**Comment by NadjibSb** [comment]
@wmathurin Thank you but we did read the doc (many times) but it's outdated.
We are using v.9.1.0
What we are actually doing, we are retrieving custom objects (we used one target class for many custom objects) using sync down, following this [sample](https://github.com/mfyc/SalesforceSDK/tree/master/hybrid/HybridSampleApps/NoteSync) . And now we are looking to do the same for sync up .

**Comment by wmathurin** [comment]
We will review the documentation. In the meantime, you can look at existing subclasses of SyncUpTarget for example of more complex sync up target class implementations.
