### ISSUE TITLE
How to sync up/down Salesforce Files(ContentDocument) via Mobile App

### ISSUE THREAD

**Issue by vivekdeshmane** [forcedotcom/SalesforceMobileSDK-Templates#318]
Hi Team,

We are trying to implement usecase in mobile app, where user will upload attachments against Campaign record and would like to store it in Salesforce as Files(ContentDocument/ContentDocumentlink/Version) instead classic Attachment object record. Howere, we observed below issues while implement it.
1. ContentDocument/ContentDocumentlink/Version not supported for smartStore/smartsync attachment data
2. No offline support

Could you please let us know, how we will achieve this usecase to support in online/offline mode?

SDK version: 8.2.0
React-native version: 0.63.2
React version: 16.11.0

Best Regards,
-Vivek

**Comment by bhariharan** [comment]
This forum is reserved for bugs/issues with the Mobile SDK. For other general queries, please use Stack Exchange.
