### ISSUE TITLE
This makes it difficult to create multiple flavors

### ISSUE THREAD

**Issue by johnjeremih** [forcedotcom/SalesforceMobileSDK-Templates#349]
I would like to know why this was made like this. Isn't this more complicated?

https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/cc2a50fc5b1ad29e33e71825d46a2ac93b97656b/AndroidNativeKotlinTemplate/app/build.gradle#L29

**Comment by wmathurin** [comment]
The generated application will be a copy of the template (with your name / package injected). So you can make any changes you require.
