### ISSUE TITLE
Can the structure of the android template be updated ?

### ISSUE THREAD

**Issue by johnjeremih** [forcedotcom/SalesforceMobileSDK-Templates#389]
https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/dev/AndroidIDPTemplate/app/build.gradle.kts#L32

Here is the original issue I submitted 

https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/2249

**Comment by wmathurin** [comment]
We are fixing that in our next release (MSDK 12.0) - see https://github.com/forcedotcom/SalesforceMobileSDK-Templates/pull/390
