### ISSUE TITLE
Configuring Passwordless Login for a ForceReact Application? 

### ISSUE THREAD

**Issue by Dev-Pradeep-NS** [forcedotcom/SalesforceMobileSDK-Templates#420]
I am currently working on a mobile application using the Salesforce Mobile SDK(forcereact) and would like to implement passwordless login for enhanced user experience and security.

Thanks in advance

**Comment by brandonpage** [comment]
We currently have no plans to make the Native Login APIs available in our React Native library or to create a React Native template that showcases the native feature.
