### ISSUE TITLE
Could not find a match for URL Unable to set sandbox url for NativeLogin in Kotlin 

### ISSUE THREAD

**Issue by johnjeremih** [forcedotcom/SalesforceMobileSDK-Templates#435]
I'm getting this error. Native Login Authorization Error: [{"errorCode":"NOT_FOUND","message":"Could not find a match forURL"}]``

![image](https://github.com/user-attachments/assets/73268df1-833f-4200-99c6-e5cb3b094e29)

I already updated the bootconfig.xml and servers.xml. It works with Salesforce login but not in the native. 
![image](https://github.com/user-attachments/assets/e30e3a5a-de67-4be2-998f-89145d649bad)

**Comment by brandonpage** [comment]
Sounds like you are using the new Native Login feature?  Please read [the documentation](https://developer.salesforce.com/docs/platform/mobile-sdk/guide/native-login-experience-cloud.html#set-up-native-login-on-android).  Native Login does not use values from servers.xml or bootconfig.xml.  

Are you sure you have done all [the necessary server side setup](https://help.salesforce.com/s/articleView?id=sf.headless_identity_customers_overview.htm&type=5)?

**Comment by wmathurin** [comment]
Closing. 

Hopefully the pointers given by @brandonpage 2 months ago were sufficient to resolve what seemed like a setup issue.
