### ISSUE TITLE
createWithTemplate results in error

### ISSUE THREAD

**Issue by syedtariq2013** [forcedotcom/SalesforceMobileSDK-Templates#57]
`$ forceios createWithTemplate
Enter URI of repo containing template application: /Users/syedtariq/icloud/Documents/GitHub/SalesforceMobileSDK-Templates
Enter your application name: SFTest3
Enter the package name for your app (com.mycompany.myapp): com.syedtariq.SFTest3
'com.syedtariq.SFTest3' is not a valid package name.
Enter the package name for your app (com.mycompany.myapp): com.syedtariq.sftest3
Enter your organization name (Acme, Inc.): clearesult
Enter output directory for your app (leave empty for the current directory):
forceios failed

Path must be a string. Received undefined`

**Comment by wmathurin** [comment]
SalesforceMobileSDK-Templates contains multiple templates and is used when doing ```forceios create```. 
```forceios createWithTemplate``` can only be used with single template repo e.g https://github.com/forcedotcom/SmartSyncExplorerReactNative

You need to pass a proper URI, for a local directory it would be file:///path-to-the-template
